server:
  # 指定Tomcat端口
  port: 8001

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    # 给这个服务取名叫做：glmc-qygl
    name: glmc-qygl
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?useUnicode=true&characterEncoding=gbk&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.gljt.providerorder.bean
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.gljt.providerorder.mapper: DEBUG

mq:
  topicname: StockTopic
  nameserver:
    addr: localhost:9876