server:
  # 指定Tomcat端口
  port: 8004

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    # 给这个服务取名叫做：glmc-bxd
    name: glmc-shy
  datasource:
    url: jdbc:mysql://localhost:3306/glmc?useUnicode=true&characterEncoding=gbk&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.gljt.provideritem.bean
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.gljt.provideritem.mapper: DEBUG
mq:
  topicname: StockTopic
  nameserver:
    addr: localhost:9876